language: node_js
node_js:
  - "14.15.0"
cache:
  # Yarn 2 caches to the local .yarn directory, not the Travis default `$HOME/.yarn`
  directories:
    - ./.yarn/cache
branches:
  only:
    - master
script: "npm run check"
install: yarn install --immutable
